refill_index:
    path:     /
    defaults: { _controller: "FinanceBundle:Refill:index" }
    methods:  GET

refill_show:
    path:     /{id}/show
    defaults: { _controller: "FinanceBundle:Refill:show" }
    methods:  GET

refill_new:
    path:     /new
    defaults: { _controller: "FinanceBundle:Refill:new" }
    methods:  [GET, POST]

refill_edit:
    path:     /{id}/edit
    defaults: { _controller: "FinanceBundle:Refill:edit" }
    methods:  [GET, POST]

refill_delete:
    path:     /{id}/delete
    defaults: { _controller: "FinanceBundle:Refill:delete" }
    methods:  DELETE
