<?php

namespace FinanceBundle\Repository;

/**
 * RefillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefillRepository extends \Doctrine\ORM\EntityRepository
{
}
